# Docker Compose for Self-Hosted Jitsi Meet
# 
# Usage:
#   docker-compose -f docker-compose-jitsi.yml up -d
#
# Then access at: http://localhost:8000
# And configure backend: http://localhost:8000/

version: '3.8'

services:
  # Jitsi Meet with Docker
  jitsi:
    image: jitsi/web:stable
    container_name: jitsi-meet
    ports:
      - "8000:80"
    environment:
      - JICOFO_AUTH_TYPE=internal
      - ENABLE_LETSENCRYPT=0
      - ENABLE_HTTP_REDIRECT=0
      - ENABLE_HSTS=0
      - VIRTUAL_HOST=localhost
      - TZ=UTC
    volumes:
      - ./jitsi-web:/config
    networks:
      - jitsi-network
    depends_on:
      - jicofo
      - jvb
    restart: unless-stopped

  jicofo:
    image: jitsi/jicofo:stable
    container_name: jitsi-jicofo
    environment:
      - XMPP_SERVER=prosody
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_PASSWORD=jicofo_password
      - JICOFO_COMPONENT_SECRET=jicofo_component_secret
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=jicofo_auth_password
      - TZ=UTC
    volumes:
      - ./jitsi-jicofo:/config
    networks:
      - jitsi-network
    depends_on:
      - prosody
    restart: unless-stopped

  prosody:
    image: jitsi/prosody:stable
    container_name: jitsi-prosody
    environment:
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_BOSH_MODULES=bosh_modules
      - XMPP_MUC_MODULES=muc_modules
      - XMPP_INTERNAL_MUC_MODULES=internal_muc_modules
      - XMPP_MODULES=xmpp_modules
      - XMPP_MUC_DOMAIN=muc.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_MODULES=xmpp_modules
      - JICOFO_COMPONENT_SECRET=jicofo_component_secret
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=jicofo_auth_password
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=jvb_password
      - JIGASI_XMPP_USER=jigasi
      - JIGASI_XMPP_PASSWORD=jigasi_password
      - JIGASI_SIP_URI=sip:jigasi@sipserver.com
      - JIGASI_SIP_PASSWORD=jigasi_sip_password
      - JIGASI_SIP_SERVER=sipserver.com
      - JIGASI_SIP_PORT=5060
      - JIGASI_SIP_TRANSPORT=UDP
      - TURN_SERVERS=turnserver.example.com
      - TURN_TRANSPORTS=udp
      - TURN_SECRET=turn_secret
      - TZ=UTC
    volumes:
      - ./jitsi-prosody:/config
    networks:
      - jitsi-network
    restart: unless-stopped

  jvb:
    image: jitsi/jvb:stable
    container_name: jitsi-jvb
    ports:
      - "10000:10000/udp"
      - "4443:4443"
    environment:
      - XMPP_SERVER=prosody
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - XMPP_PASSWORD=jvb_password
      - JICOFO_AUTH_USER=focus
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=jvb_password
      - JVB_BREWERY_MUC=jvbbrewery
      - JVB_PORT=10000
      - JVB_TCP_HARVESTER_DISABLED=true
      - JVB_TCP_PORT=4443
      - TZ=UTC
    volumes:
      - ./jitsi-jvb:/config
    networks:
      - jitsi-network
    depends_on:
      - prosody
    restart: unless-stopped

networks:
  jitsi-network:
    driver: bridge
